baseURL = "https://zhenghe-md.github.io/nerds-docs/"
languageCode = "en-us"
title = "笨学文档"
theme = "book"

[params]
  BookToC = false

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
