baseURL = "https://zhenghe-md.github.io/nerds-docs/"
languageCode = "en-us"
title = "笨学指南文档"
theme = "book"

googleAnalytics = "UA-172943223-4"
disqusShortname = "nerds-docs"
enableGitInfo = true

[menu]
[[menu.after]]
  name = "博客"
  url = "https://zhenghe-md.github.io/blog/tags/笨学指南/"
  weight = 10

[params]
  BookTheme = 'light'
  BookToC = true
  BookRepo = 'https://github.com/ZhengHe-MD/nerds-docs'
  BookEditPath = 'edit/main'

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

